### PR TITLE
Updated controllers and models to insert UserId in issues table

### PR DESCRIPTION
**Pull request by olen-d**

### CODE REVIEW

**Review by kpatel1209 — DISMISSED** [review]
looks good!

**Review by heincm — CHANGES_REQUESTED** [review]
Sent you a slack message. Take a look a let me know your thoughts.

**Review by heincm — DISMISSED** [review]
Posts to database with userID as expected. Good work!

**Review by heincm — APPROVED** [review]
Good catch, Olen.

**Review by kpatel1209 — APPROVED** [review]
reported a few issues under my username and my user id posted to the db, awesome job!

**Pull request merged**
